namespace ThirtyFiveG.Commons.Tel
{
    public class DialingCodeCollection
    {
        #region Private variables
        private static readonly DialingCode[] _dialingCodes = 
            new DialingCode[] {
                new DialingCode("93", "AF", "AFG"),
                new DialingCode("355", "AL", "ALB"),
                new DialingCode("213", "DZ", "DZA"),
                new DialingCode("1-684", "AS", "ASM"),
                new DialingCode("376", "AD", "AND"),
                new DialingCode("244", "AO", "AGO"),
                new DialingCode("1-264", "AI", "AIA"),
                new DialingCode("672", "AQ", "ATA"),
                new DialingCode("1-268", "AG", "ATG"),
                new DialingCode("54", "AR", "ARG"),
                new DialingCode("374", "AM", "ARM"),
                new DialingCode("297", "AW", "ABW"),
                new DialingCode("61", "AU", "AUS"),
                new DialingCode("43", "AT", "AUT"),
                new DialingCode("994", "AZ", "AZE"),
                new DialingCode("1-242", "BS", "BHS"),
                new DialingCode("973", "BH", "BHR"),
                new DialingCode("880", "BD", "BGD"),
                new DialingCode("1-246", "BB", "BRB"),
                new DialingCode("375", "BY", "BLR"),
                new DialingCode("32", "BE", "BEL"),
                new DialingCode("501", "BZ", "BLZ"),
                new DialingCode("229", "BJ", "BEN"),
                new DialingCode("1-441", "BM", "BMU"),
                new DialingCode("975", "BT", "BTN"),
                new DialingCode("591", "BO", "BOL"),
                new DialingCode("387", "BA", "BIH"),
                new DialingCode("267", "BW", "BWA"),
                new DialingCode("55", "BR", "BRA"),
                new DialingCode("246", "IO", "IOT"),
                new DialingCode("1-284", "VG", "VGB"),
                new DialingCode("673", "BN", "BRN"),
                new DialingCode("359", "BG", "BGR"),
                new DialingCode("226", "BF", "BFA"),
                new DialingCode("257", "BI", "BDI"),
                new DialingCode("855", "KH", "KHM"),
                new DialingCode("237", "CM", "CMR"),
                new DialingCode("1", "CA", "CAN"),
                new DialingCode("238", "CV", "CPV"),
                new DialingCode("1-345", "KY", "CYM"),
                new DialingCode("236", "CF", "CAF"),
                new DialingCode("235", "TD", "TCD"),
                new DialingCode("56", "CL", "CHL"),
                new DialingCode("86", "CN", "CHN"),
                new DialingCode("61", "CX", "CXR"),
                new DialingCode("61", "CC", "CCK"),
                new DialingCode("57", "CO", "COL"),
                new DialingCode("269", "KM", "COM"),
                new DialingCode("682", "CK", "COK"),
                new DialingCode("506", "CR", "CRI"),
                new DialingCode("385", "HR", "HRV"),
                new DialingCode("53", "CU", "CUB"),
                new DialingCode("599", "CW", "CUW"),
                new DialingCode("357", "CY", "CYP"),
                new DialingCode("420", "CZ", "CZE"),
                new DialingCode("243", "CD", "COD"),
                new DialingCode("45", "DK", "DNK"),
                new DialingCode("253", "DJ", "DJI"),
                new DialingCode("1-767", "DM", "DMA"),
                new DialingCode("1-809, 1-829, 1-849", "DO", "DOM"),
                new DialingCode("670", "TL", "TLS"),
                new DialingCode("593", "EC", "ECU"),
                new DialingCode("20", "EG", "EGY"),
                new DialingCode("503", "SV", "SLV"),
                new DialingCode("240", "GQ", "GNQ"),
                new DialingCode("291", "ER", "ERI"),
                new DialingCode("372", "EE", "EST"),
                new DialingCode("251", "ET", "ETH"),
                new DialingCode("500", "FK", "FLK"),
                new DialingCode("298", "FO", "FRO"),
                new DialingCode("679", "FJ", "FJI"),
                new DialingCode("358", "FI", "FIN"),
                new DialingCode("33", "FR", "FRA"),
                new DialingCode("689", "PF", "PYF"),
                new DialingCode("241", "GA", "GAB"),
                new DialingCode("220", "GM", "GMB"),
                new DialingCode("995", "GE", "GEO"),
                new DialingCode("49", "DE", "DEU"),
                new DialingCode("233", "GH", "GHA"),
                new DialingCode("350", "GI", "GIB"),
                new DialingCode("30", "GR", "GRC"),
                new DialingCode("299", "GL", "GRL"),
                new DialingCode("1-473", "GD", "GRD"),
                new DialingCode("1-671", "GU", "GUM"),
                new DialingCode("502", "GT", "GTM"),
                new DialingCode("44-1481", "GG", "GGY"),
                new DialingCode("224", "GN", "GIN"),
                new DialingCode("245", "GW", "GNB"),
                new DialingCode("592", "GY", "GUY"),
                new DialingCode("509", "HT", "HTI"),
                new DialingCode("504", "HN", "HND"),
                new DialingCode("852", "HK", "HKG"),
                new DialingCode("36", "HU", "HUN"),
                new DialingCode("354", "IS", "ISL"),
                new DialingCode("91", "IN", "IND"),
                new DialingCode("62", "ID", "IDN"),
                new DialingCode("98", "IR", "IRN"),
                new DialingCode("964", "IQ", "IRQ"),
                new DialingCode("353", "IE", "IRL"),
                new DialingCode("44-1624", "IM", "IMN"),
                new DialingCode("972", "IL", "ISR"),
                new DialingCode("39", "IT", "ITA"),
                new DialingCode("225", "CI", "CIV"),
                new DialingCode("1-876", "JM", "JAM"),
                new DialingCode("81", "JP", "JPN"),
                new DialingCode("44-1534", "JE", "JEY"),
                new DialingCode("962", "JO", "JOR"),
                new DialingCode("7", "KZ", "KAZ"),
                new DialingCode("254", "KE", "KEN"),
                new DialingCode("686", "KI", "KIR"),
                new DialingCode("383", "XK", "XKX"),
                new DialingCode("965", "KW", "KWT"),
                new DialingCode("996", "KG", "KGZ"),
                new DialingCode("856", "LA", "LAO"),
                new DialingCode("371", "LV", "LVA"),
                new DialingCode("961", "LB", "LBN"),
                new DialingCode("266", "LS", "LSO"),
                new DialingCode("231", "LR", "LBR"),
                new DialingCode("218", "LY", "LBY"),
                new DialingCode("423", "LI", "LIE"),
                new DialingCode("370", "LT", "LTU"),
                new DialingCode("352", "LU", "LUX"),
                new DialingCode("853", "MO", "MAC"),
                new DialingCode("389", "MK", "MKD"),
                new DialingCode("261", "MG", "MDG"),
                new DialingCode("265", "MW", "MWI"),
                new DialingCode("60", "MY", "MYS"),
                new DialingCode("960", "MV", "MDV"),
                new DialingCode("223", "ML", "MLI"),
                new DialingCode("356", "MT", "MLT"),
                new DialingCode("692", "MH", "MHL"),
                new DialingCode("222", "MR", "MRT"),
                new DialingCode("230", "MU", "MUS"),
                new DialingCode("262", "YT", "MYT"),
                new DialingCode("52", "MX", "MEX"),
                new DialingCode("691", "FM", "FSM"),
                new DialingCode("373", "MD", "MDA"),
                new DialingCode("377", "MC", "MCO"),
                new DialingCode("976", "MN", "MNG"),
                new DialingCode("382", "ME", "MNE"),
                new DialingCode("1-664", "MS", "MSR"),
                new DialingCode("212", "MA", "MAR"),
                new DialingCode("258", "MZ", "MOZ"),
                new DialingCode("95", "MM", "MMR"),
                new DialingCode("264", "NA", "NAM"),
                new DialingCode("674", "NR", "NRU"),
                new DialingCode("977", "NP", "NPL"),
                new DialingCode("31", "NL", "NLD"),
                new DialingCode("599", "AN", "ANT"),
                new DialingCode("687", "NC", "NCL"),
                new DialingCode("64", "NZ", "NZL"),
                new DialingCode("505", "NI", "NIC"),
                new DialingCode("227", "NE", "NER"),
                new DialingCode("234", "NG", "NGA"),
                new DialingCode("683", "NU", "NIU"),
                new DialingCode("850", "KP", "PRK"),
                new DialingCode("1-670", "MP", "MNP"),
                new DialingCode("47", "NO", "NOR"),
                new DialingCode("968", "OM", "OMN"),
                new DialingCode("92", "PK", "PAK"),
                new DialingCode("680", "PW", "PLW"),
                new DialingCode("970", "PS", "PSE"),
                new DialingCode("507", "PA", "PAN"),
                new DialingCode("675", "PG", "PNG"),
                new DialingCode("595", "PY", "PRY"),
                new DialingCode("51", "PE", "PER"),
                new DialingCode("63", "PH", "PHL"),
                new DialingCode("64", "PN", "PCN"),
                new DialingCode("48", "PL", "POL"),
                new DialingCode("351", "PT", "PRT"),
                new DialingCode("1-787, 1-939", "PR", "PRI"),
                new DialingCode("974", "QA", "QAT"),
                new DialingCode("242", "CG", "COG"),
                new DialingCode("262", "RE", "REU"),
                new DialingCode("40", "RO", "ROU"),
                new DialingCode("7", "RU", "RUS"),
                new DialingCode("250", "RW", "RWA"),
                new DialingCode("590", "BL", "BLM"),
                new DialingCode("290", "SH", "SHN"),
                new DialingCode("1-869", "KN", "KNA"),
                new DialingCode("1-758", "LC", "LCA"),
                new DialingCode("590", "MF", "MAF"),
                new DialingCode("508", "PM", "SPM"),
                new DialingCode("1-784", "VC", "VCT"),
                new DialingCode("685", "WS", "WSM"),
                new DialingCode("378", "SM", "SMR"),
                new DialingCode("239", "ST", "STP"),
                new DialingCode("966", "SA", "SAU"),
                new DialingCode("221", "SN", "SEN"),
                new DialingCode("381", "RS", "SRB"),
                new DialingCode("248", "SC", "SYC"),
                new DialingCode("232", "SL", "SLE"),
                new DialingCode("65", "SG", "SGP"),
                new DialingCode("1-721", "SX", "SXM"),
                new DialingCode("421", "SK", "SVK"),
                new DialingCode("386", "SI", "SVN"),
                new DialingCode("677", "SB", "SLB"),
                new DialingCode("252", "SO", "SOM"),
                new DialingCode("27", "ZA", "ZAF"),
                new DialingCode("82", "KR", "KOR"),
                new DialingCode("211", "SS", "SSD"),
                new DialingCode("34", "ES", "ESP"),
                new DialingCode("94", "LK", "LKA"),
                new DialingCode("249", "SD", "SDN"),
                new DialingCode("597", "SR", "SUR"),
                new DialingCode("47", "SJ", "SJM"),
                new DialingCode("268", "SZ", "SWZ"),
                new DialingCode("46", "SE", "SWE"),
                new DialingCode("41", "CH", "CHE"),
                new DialingCode("963", "SY", "SYR"),
                new DialingCode("886", "TW", "TWN"),
                new DialingCode("992", "TJ", "TJK"),
                new DialingCode("255", "TZ", "TZA"),
                new DialingCode("66", "TH", "THA"),
                new DialingCode("228", "TG", "TGO"),
                new DialingCode("690", "TK", "TKL"),
                new DialingCode("676", "TO", "TON"),
                new DialingCode("1-868", "TT", "TTO"),
                new DialingCode("216", "TN", "TUN"),
                new DialingCode("90", "TR", "TUR"),
                new DialingCode("993", "TM", "TKM"),
                new DialingCode("1-649", "TC", "TCA"),
                new DialingCode("688", "TV", "TUV"),
                new DialingCode("1-340", "VI", "VIR"),
                new DialingCode("256", "UG", "UGA"),
                new DialingCode("380", "UA", "UKR"),
                new DialingCode("971", "AE", "ARE"),
                new DialingCode("44", "GB", "GBR"),
                new DialingCode("1", "US", "USA"),
                new DialingCode("598", "UY", "URY"),
                new DialingCode("998", "UZ", "UZB"),
                new DialingCode("678", "VU", "VUT"),
                new DialingCode("379", "VA", "VAT"),
                new DialingCode("58", "VE", "VEN"),
                new DialingCode("84", "VN", "VNM"),
                new DialingCode("681", "WF", "WLF"),
                new DialingCode("212", "EH", "ESH"),
                new DialingCode("967", "YE", "YEM"),
                new DialingCode("260", "ZM", "ZMB"),
                new DialingCode("263", "ZW", "ZWE")
            };
        #endregion

        #region Public properties
        public virtual DialingCode[] DialingCodes { get { return _dialingCodes; } }
        #endregion

        #region Public methods
        public DialingCode MatchDialingCode(string telephone)
        {
            DialingCode matched = null;
            foreach(DialingCode dialingCode in DialingCodes)
            {
                if (telephone.StartsWith(dialingCode.Code) 
                    && (matched == null || dialingCode.Code.Length > matched.Code.Length))
                    matched = dialingCode;
            }
            return matched;
        }
        #endregion

    }
}
